### ISSUE TITLE
[BUG] Devcheck failing attempting to install Pydra

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-dcm2niix#9]
The following GH "devcheck" action 

```yaml
  devcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]  # Check oldest and newest versions
        pip-flags: ['', '--editable']
        pydra:
        - 'pydra'
        - '--editable git+https://github.com/nipype/pydra.git#egg=pydra'
```

is failing attempting to install Pydra with the following error

```
Building wheels for collected packages: pydra
  Building editable for pydra (pyproject.toml): started
  Building editable for pydra (pyproject.toml): finished with status 'done'
  Created wheel for pydra: filename=pydra-0.19+11.g86671ad-0.editable-py3-none-any.whl size=5199 sha256=2a45a9adfdbc8e40523a05efb3a1ad06cd08fcdfea1bc58ba98a65e46a595[49](https://github.com/nipype/pydra-dcm2niix/runs/8180529906?check_suite_focus=true#step:5:50)1
  Stored in directory: /tmp/pip-ephem-wheel-cache-2hq3au8v/wheels/26/7d/56/1c4c8dba03f6beefc3ae037df68e59cb6782d3cc9325306b5f
Successfully built pydra
Installing collected packages: urllib3, idna, filelock, cloudpickle, ci-info, charset-normalizer, certifi, attrs, requests, etelemetry, pydra
Successfully installed attrs-22.1.0 certifi-2022.6.15 charset-normalizer-2.1.1 ci-info-0.3.0 cloudpickle-2.1.0 etelemetry-0.3.0 filelock-3.8.0 idna-3.3 pydra-0.19+11.g86671ad requests-2.28.1 urllib3-1.26.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pydra' has no attribute '__version__'
```

not sure if this is just an issue with the Pydra main branch in its current state (likely I think as I didn't run into this error before) or something about how versioneer is being used
